version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: fontys
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
  api:
    depends_on: ["db"]
    image: ggc-followerservice-api
    restart: always
    build:
      context: .
      target: dev
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=fontys
volumes:
  db-data:
